version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host('hugobarbosa.fr') || Host('www.hugobarbosa.fr')"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

    restart: unless-stopped
    networks:
      - web
      
networks:
  web:
    external: true